--batch-limit: '5000000'
--batchsize: '8192'
--device: '0'
--dump-every: '900'
--help: false
--house-degree: '0'
--log-interval: '1'
--model-type: iwae
--nhidden: '256'
--nlatent: '16'
--nmap: '1'
--runtime: '3600'
--time-print: '60'
--time-sample: '10'
--vae-samples: '3'
--vis: null
-o: elbo_3_setup_run_2
<data.mat>: ./data/MSRC12-X-d60.mat
