--batch-limit: '100'
--batchsize: '8192'
--data: pose
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--init-learn: 1e-4
--init-model: init_house_3.h5
--init-opt: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '5'
--model-type: householder
--nhidden: '512'
--nlatent: '16'
--runtime: '18000'
--temp-epoch: '200'
--time-print: '600'
--trans: '10'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: 10_transform_2_run_3
