--batch-limit: '5000000'
--batchsize: '8192'
--device: '0'
--dump-every: '900'
--help: false
--house-degree: '1'
--log-interval: '100'
--model-type: vae
--nhidden: '128'
--nlatent: '2'
--nmap: '1'
--runtime: '300'
--test: '1000'
--time-print: '60'
--time-sample: '60'
--vae-samples: '1'
--vis: null
-o: compare_1_debug
<data.mat>: ./data/MSRC12-X-d60.mat
