--batch-limit: '1000'
--batchsize: '16384'
--data: pose
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--init-learn: 1e-4
--init-model: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '5'
--model-type: iaf
--nhidden: '512'
--nlatent: '16'
--nlayers: '4'
--ntrans: '8'
--runtime: '1000000'
--temp-epoch: '200'
--time-print: '600'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: pose_samples_1_8t_run_1
