--batch-limit: '5000000'
--batchsize: '65536'
--device: '0'
--dump-every: '900'
--help: false
--house-degree: '1'
--log-interval: '100'
--model-type: vae
--nhidden: '512'
--nlatent: '50'
--nmap: '1'
--runtime: '10800'
--test: '600000'
--time-print: '600'
--time-sample: '12000'
--vae-samples: '1'
--vis: null
-o: combine_factors_2
<data.mat>: ./data/MSRC12-X-d60.mat
