--batch-limit: '5000'
--batchsize: '4096'
--data: mnist
--device: '0'
--dump-every: '900'
--epoch-sample: '100'
--help: false
--init-learn: 10e-4
--init-model: init_vae_mnist.h5
--init-opt: none
--init-temp: '0'
--learn-decay: '0'
--log-interval: '10'
--model-type: vae
--nhidden: '200'
--nlatent: '50'
--runtime: '1000000'
--temp-epoch: '200'
--time-print: '600'
--trans: '1'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: debug_no_learn_decay_1
