--batch-limit: '5'
--batchsize: '16384'
--data: pose
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--init-learn: 1e-4
--init-model: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '5'
--model-type: iwae
--nhidden: '512'
--nlatent: '16'
--nlayers: '4'
--ntrans: '2'
--runtime: '180000'
--temp-epoch: '200'
--time-print: '1'
--vae-samples: '2'
--vis: null
--weight-decay: '0'
-o: debug_1
