--batch-limit: '1000'
--batchsize: '4096'
--data: mnist
--device: '0'
--dump-every: '900'
--epoch-sample: '100'
--help: false
--init-learn: 10e-4
--init-model: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '10'
--model-type: iaf
--nhidden: '200'
--nlatent: '50'
--nlayers: '2'
--ntrans: '1'
--runtime: '1000000'
--temp-epoch: '1'
--time-print: '600'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: seb_mnist_samples_1_t_run_1
