--batch-limit: '5000000'
--batchsize: '8192'
--device: '0'
--dump-every: '900'
--help: false
--house-degree: '1'
--log-interval: '100'
--model-type: vae
--nhidden: '256'
--nlatent: '16'
--nmap: '1'
--runtime: '3600'
--test: '600000'
--time-print: '600'
--time-sample: '1200'
--vae-samples: '1'
--vis: null
-o: small_train
<data.mat>: ./data/MSRC12-X-d60.mat
