--batch-limit: '50000'
--batchsize: '16384'
--data: pose
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--log-interval: '5'
--model-type: iwae
--nhidden: '512'
--nlatent: '16'
--runtime: '18000'
--time-print: '600'
--trans: '2'
--vae-samples: '2'
--vis: null
-o: long_4
