--batch-limit: '5000000'
--batchsize: '8192'
--device: '0'
--dump-every: '900'
--help: false
--house-degree: '0'
--log-interval: '1'
--model-type: vae
--nhidden: '512'
--nlatent: '2'
--nmap: '1'
--runtime: '10800'
--time-print: '300'
--time-sample: '30'
--vae-samples: '1'
--vis: null
-o: poster_2_latent_dims
<data.mat>: ./data/MSRC12-X-d60.mat
