#!/bin/bash

# Increasing number of samples in each for loop

#

#samples=(1 2 5)


for i in `seq 1 1`;
do
#for j in "${samples[@]}"
#do 	
./train_seb.py -g 0 -o 'seb_mnist_samples_1_'$1't_run_'$i --model-type iaf --vae-samples 1 --ntrans 1 --nlatent 50 --nhidden 200 --nlayers 2\
 -b 4096 --batch-limit 1000 -t 1000000 --time-print 600 --epoch-sample 100 --log-interval 10 --data mnist \
 --init-temp 0 --temp-epoch 1  --init-learn 10e-4 --learn-decay 3e-3 --weight-decay 0 --init-model none 
#done
done
