#!/bin/bash

# Increasing number of samples in each for loop


for i in `seq 1 1`;
do
./train.py -g 0 -o debug_$i --model-type planar --vae-samples 2 --ntrans 2 --nlatent 50 --nhidden 200 --nlayers 2\
 -b 4096 --batch-limit 5 -t 180000 --time-print 1 --epoch-sample 200 --log-interval 5 --data mnist\
 --init-temp 0 --temp-epoch 200 --init-learn 1e-3 --learn-decay 3e-4 --weight-decay 0 --init-model none 
done
#	
