#!/bin/bash

# Increasing number of samples in each for loop

#for i in `seq 1 5`;
#do
#i=3
#	for j in `seq 1 3`;	 
#	do
#		./train.py -g 0 -o 'elbo_'$j'_setup_run_'$i --model-type iwae --nlatent 16 --nhidden 256 --house-degree 0 --nmap 1 --vae-samples $j -b 8192 --batch-limit 5000000 -t 3600 --time-print 60 --time-sample 10 --log-interval 1 ./data/MSRC12-X-d60.mat 
#	done
#done
for i in `seq 1 3`;
do
./train_1.py -g 0 -o 10_transform_2_run_$i --model-type householder --vae-samples 1 --trans 10 --nlatent 16 --nhidden 512 \
-b 8192 --batch-limit 100 -t 18000 --time-print 600 --epoch-sample 200 --log-interval 5 --data pose\
 --init-temp 0 --temp-epoch 200 --init-learn 1e-4 --learn-decay 3e-3 --weight-decay 0 --init-model init_house_$i.h5 --init-opt none
done
#	
