#!/bin/bash

./train.py -g 0 -o debug --model-type vae --house-degree 1 --nmap 1 --vae-samples 2 -b 8192 --batch-limit 50000 -t 300 --time-print 5 --time-sample 1200 --log-interval 100 --test 8193 ./data/MSRC12-X-d60.mat

