#!/bin/bash

# Increasing number of samples in each for loop

#for i in `seq 1 5`;
#do
#i=3
#	for j in `seq 1 3`;	 
#	do
#		./train.py -g 0 -o 'elbo_'$j'_setup_run_'$i --model-type iwae --nlatent 16 --nhidden 256 --house-degree 0 --nmap 1 --vae-samples $j -b 8192 --batch-limit 5000000 -t 3600 --time-print 60 --time-sample 10 --log-interval 1 ./data/MSRC12-X-d60.mat 
#	done
#done

#
for i in `seq 1 1`;
do	
./train.py -g 0 -o 512_50_run_temp_$i --model-type vae --vae-samples 1 --trans 1 --nlatent 50 --nhidden 512 \
 -b 4096 --batch-limit 20 -t 1000000 --time-print 1 --epoch-sample 100 --log-interval 10 --data mnist \
 --init-temp 0 --temp-epoch 1 --init-learn 1e-4 --learn-decay 3e-3 --weight-decay 0 --init-model none --init-opt none
done
