#!/bin/bash

# Increasing number of samples in each for loop

#for i in `seq 1 5`;
#do
i=3
	for j in `seq 1 3`;	 
	do
		./train.py -g 0 -o 'elbo_'$j'_setup_run_'$i --model-type vae --nlatent 16 --nhidden 256 --house-degree 0 --nmap 1 --vae-samples $j -b 8192 --batch-limit 5000000 -t 3600 --time-print 300 --time-sample 30 --log-interval 1 ./data/MSRC12-X-d60.mat 
	done
#done
