#!/bin/bash

# Increasing number of samples in each for loop

#
for i in `seq 1 1`;
do	
./train.py -g 0 -o debug_no_learn_decay_$i --model-type vae --vae-samples 1 --trans 1 --nlatent 50 --nhidden 200 \
 -b 4096 --batch-limit 5000 -t 1000000 --time-print 600 --epoch-sample 100 --log-interval 10 --data mnist \
 --init-temp 0 --temp-epoch 200 --init-learn 10e-4 --learn-decay 0 --weight-decay 0 --init-model init_vae_mnist.h5 --init-opt none
done
