--batch-limit: '5000'
--batchsize: '4096'
--data: mnist
--device: '0'
--dump-every: '900'
--epoch-sample: '100'
--help: false
--init-learn: 1e-4
--init-model: none
--init-opt: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '10'
--model-type: vae
--nhidden: '128'
--nlatent: '32'
--runtime: '1000000'
--temp-epoch: '1'
--time-print: '600'
--trans: '1'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: 128_32_run_3
