--batch-limit: '200'
--batchsize: '16384'
--data: pose
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--init-learn: 1e-4
--init-model: init_iwae_5s_1.h5
--init-opt: none
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '5'
--model-type: iwae
--nhidden: '512'
--nlatent: '16'
--runtime: '180000'
--temp-epoch: '200'
--time-print: '600'
--trans: '1'
--vae-samples: '5'
--vis: null
--weight-decay: '0'
-o: 2_samples_5_run_1
