--batch-limit: '5'
--batchsize: '4096'
--data: mnist
--device: '0'
--dump-every: '900'
--epoch-sample: '200'
--help: false
--init-learn: 1e-3
--init-model: none
--init-temp: '0'
--learn-decay: 3e-4
--log-interval: '5'
--model-type: iaf
--nhidden: '200'
--nlatent: '50'
--nlayers: '2'
--ntrans: '2'
--runtime: '180000'
--temp-epoch: '200'
--time-print: '1'
--vae-samples: '2'
--vis: null
--weight-decay: '0'
-o: debug_1
