--batch-limit: '50'
--batchsize: '1024'
--data: mnist
--device: '0'
--dump-every: '900'
--epoch-sample: '10'
--help: false
--init-learn: 1e-5
--init-temp: '0'
--learn-decay: 3e-3
--log-interval: '100'
--model-type: vae
--nhidden: '512'
--nlatent: '32'
--runtime: '300'
--temp-epoch: '600'
--time-print: '1'
--trans: '1'
--vae-samples: '1'
--vis: null
--weight-decay: '0'
-o: mnist_1
